# Generated by Django 4.0.1 on 2022-01-26 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_rename_recipeingredients_recipeingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='FavouritesItem',
        ),
    ]
